### ISSUE TITLE
TypeError: files() missing 1 required positional argument: 'package'

### ISSUE THREAD

**Issue by subsetpark** [gitonthescene/ngnk-lsp#1]
This error comes up when running `ngnklsp` either through poetry or having installed the wheel file. 

I can dig into it further but it seems that there's a version mismatch where my version of whatever the type of `resources` is requires a single argument to the `files()` method.

```
Traceback (most recent call last):
  File "/home/zax/.local/bin/ngnklsp", line 5, in <module>
    from ngnk_lsp import main
  File "/home/zax/.local/share/pipx/venvs/ngnk-lsp/lib/python3.11/site-packages/ngnk_lsp/__init__.py", line 1, in <module>
    import ngnk_lsp.ngnklsp as ngnklsp
  File "/home/zax/.local/share/pipx/venvs/ngnk-lsp/lib/python3.11/site-packages/ngnk_lsp/ngnklsp.py", line 21, in <module>
    legend = semantic.init()
             ^^^^^^^^^^^^^^^
  File "/home/zax/.local/share/pipx/venvs/ngnk-lsp/lib/python3.11/site-packages/ngnk_lsp/semantic.py", line 9, in init
    with resources.as_file(resources.files().joinpath("semantic.k")) as semantick:
```

**Comment by gitonthescene** [comment]
Can you post the error message too?

**Comment by subsetpark** [comment]
Sorry, the error message is the title of the issue: `TypeError: files() missing 1 required positional argument: 'package'`

**Comment by subsetpark** [comment]
For what it's worth, it seems that all that is doing is getting the filename `semantic.k`? 

I was able to replace it with this:

```
    dir_path = os.path.dirname(os.path.realpath(__file__))
    filename = os.path.join(dir_path, "semantic.k")
    k.Kx("\\l "+str(filename), ())
```

but maybe it doesn't accomplish the same thing.

**Comment by Rik-de-Kort** [comment]
In Python 3.12 the `package` argument is optional ([docs](https://docs.python.org/3.12/library/importlib.resources.html#importlib.resources.files)), but on 3.11 it is not ([docs](https://docs.python.org/3.11/library/importlib.resources.html#importlib.resources.files)). That's why it's not working on your machine.

**Comment by subsetpark** [comment]
Seems like the behaviour of the call when no argument is passed is the same as if "ngnk_lsp" were passed.

**Comment by gitonthescene** [comment]
Thanks for the report and thanks to @Rik-de-Kort for spotting the issue.  I've used a [forward compatible shim](https://github.com/gitonthescene/ngnk-lsp/commit/043674cffd649f5ca2184a626a424e5321391b48)[1] to get this to work with Python 3.11.  Would you mind giving this a spin?  It seemed to work on my desktop.

[1] The commit says backwards compatible, but now I realize it's the wrong word.

**Comment by gitonthescene** [comment]
I've pushed this to a new pre-release.  I'll leave this open for a week in case you have any issues with it, otherwise I'll consider this issue resolved.

Regards

**Comment by gitonthescene** [comment]
I'm going to assume all is good.  Feel free to reopen if you have further issues.
